config/routes.rb
Rails.application.routes.draw do
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'

  get '/signup', to: 'users#new'
  resources :users
  post '/signup', to: 'users#create'
  resources :account_activations, only: [:edit]

  resources :books

  resources :borrowings,       only: [:index, :create, :destroy, :update]
  get '/borrowing/all', to: "borrowings#borrowing_all"
  patch '/approve', to: "borrowings#approve"
  patch '/deny_renew', to: "borrowings#deny_renew_request"
  patch '/deny_borrow', to: "borrowings#deny_borrow_request"
  get '/return', to: "borrowings#return_book"

  get '/search', to: 'search#search'


  resources :return_books, only: [:index]

end

app/models/borrowing.rb
class Borrowing < ApplicationRecord
  belongs_to :user, class_name: "User"
  belongs_to :book, class_name: "Book"

  def self.requesting
  	Borrowing.where(["status != ?", 1])
  end

  def self.borrowed
    Borrowing.where(["status == ? or status == ?", 1, 2])
  end

  def time_remaining
  	time_remaining = self.book.maximum_days - (Time.zone.now.to_date  - self.renew_at.to_date).to_i
  	if time_remaining < 0
  		time_remaining = 0
  	end
  	time_remaining
  end

end

app/controllers/borrowings_controller.rb
class BorrowingsController < ApplicationController
	before_action :logged_in_user
  before_action :librarian_user, only: [:approve, :deny_borrow_request, :deny_renew_request, :return_book]

  def index
    if !current_user.librarian?
      @borrowings = current_user.borrowings.paginate(:page => params[:page])
    else
      @borrowings = Borrowing.requesting.paginate(:page => params[:page])
    end
  end

  def borrowing_all
    if current_user.librarian?
      @borrowings = Borrowing.borrowed.paginate(:page => params[:page])
    end
  end

	def create #borrow
    @book = Book.find(params[:book_id])
    if @book.available?
      if current_user.borrowing.count == 5
        flash[:danger] = "Your borrowings is limited. You cann't borrow over 5 books!"
        redirect_to @book
      else
        current_user.borrow(@book)
        respond_to do |format|
        format.html { redirect_to @book }
        format.js
        end
      end
    else
      flash[:danger] = "Sorry! Book is limited!"
      redirect_to @book
    end
	end

  def update #renew request
    @borrowing = Borrowing.find(params[:id])
    if @borrowing.status == 0
      flash[:danger] = "#{@borrowing.book.title} have not approved!"
    else
      if @borrowing.renew_num >= 3
        flash[:danger] = "You cannot renew #{@borrowing.book.title}"
      else
        @borrowing.update_attribute(:renew_num, @borrowing.renew_num + 1)
        @borrowing.update_attribute(:status, 2)
        flash[:success] = "Renew request successfull #{@borrowing.book.title} have to wait to approve!"
      end
    end
    redirect_to borrowings_path
  end

  def deny_renew_request
    if @borrowing = Borrowing.find(params[:borrowing_id])
      @borrowing.update_attribute(:renew_num, @borrowing.renew_num - 1)
      @borrowing.update_attribute(:status, 1)
    else
      flash[:danger] = "Error. Try again!"
    end
    redirect_to borrowings_path
  end

  def approve # for borrow
    if @borrowing = Borrowing.find(params[:borrowing_id])
      @borrowing.update_attribute(:status, 1)
      @borrowing.update_attribute(:renew_at, Time.zone.now)
    else
      flash[:danger] = "Error. Try again!"
    end
    redirect_to borrowings_path
  end

  def deny_borrow_request
    if @borrowing = Borrowing.find(params[:borrowing_id])
      @borrowing.user.unborrow(@borrowing.book)
    else
      flash[:danger] = "Error. Try again!"
    end
    redirect_to borrowings_path
  end


  def destroy 
    borrowing = Borrowing.find(params[:id])
    borrowing.user.unborrow(borrowing.book)
    flash[:success] = "Book deleted"
    redirect_back_or(return_books_path) 
  end

  def return_book
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @borrowings = @user.borrowings.paginate(:page => params[:page])
    end
  end

  private
    def librarian_user
      if current_user.nil?
        redirect_to (root_url)
      else
        redirect_to (root_url) unless current_user.librarian?
      end
    end

end

app/helpers/borrowings_helper.rb
module BorrowingsHelper
end

app/views/borrowings/_borrowing.html.erb
<li>
  <% if !current_user.librarian? %>
    <%= render :partial => 'borrowing_user', :locals => { :borrowing => borrowing } %>
  <% else %>
    <%= render :partial => 'borrowing_librarian', :locals => { :borrowing => borrowing } %>
  <% end %>

</li>

app/views/borrowings/_borrowing_librarian.html.erb
<%= link_to borrowing.book.title, borrowing.book %>
  <p>Author: <%= borrowing.book.author %></p>
  <p>Publisher: <%= borrowing.book.publisher %></p>
  <p>Renew number: <%= borrowing.renew_num %></p>
  <p>Timeout: <%= borrowing.time_remaining %> days</p>
  <p>Borrow by: <%= link_to borrowing.user.name, borrowing.user %></p> 

<% if borrowing.status == 0 %>

  <%= form_for(borrowing, url: approve_path) do |f| %>
    <div><%= hidden_field_tag :borrowing_id, borrowing.id %></div>
    <%= f.submit "Approve", class: "btn btn-primary col-md-1" %>
  <% end %>

  <%= form_for(borrowing, url: deny_borrow_path) do |f| %>
    <div><%= hidden_field_tag :borrowing_id, borrowing.id %></div>
    <%= f.submit "Deny", class: "btn btn-primary col-md-1" %>
  <% end %>

  <span id="requesting"> 
      <%= "Borrow Requesting" %>
  </span>

<% elsif borrowing.status == 2 %>
  <%= form_for(borrowing, url: approve_path) do |f| %>
    <div><%= hidden_field_tag :borrowing_id, borrowing.id %></div>
    <%= f.submit "Approve", class: "btn btn-primary col-md-1" %>
    
  <% end %>

  <%= form_for(borrowing, url: deny_renew_path) do |f| %>
    <div><%= hidden_field_tag :borrowing_id, borrowing.id %></div>
    <%= f.submit "Deny", class: "btn btn-primary col-md-1" %>
  <% end %>

  <span id="requesting"> 
        <%= "Renew Requesting" %>
    </span>
<% end %>

app/views/borrowings/_borrowing_user.html.erb
<%= link_to borrowing.book.title, borrowing.book %>
  <p>Author: <%= borrowing.book.author %></p>
  <p>Publisher: <%= borrowing.book.publisher %></p>
  <p>Renew number: <%= borrowing.renew_num %></p>
  <p>Timeout: <%= borrowing.time_remaining %> days</p>


<%= form_for(borrowing, remote: true) do |f| %>
  <div><%= hidden_field_tag :borrowing_id, borrowing.id %></div>
  
  <% if borrowing.status == 0  %>
    <%= f.submit "Renew", class: "btn btn-primary col-md-1 renew-btn", disabled: true %>
    <span id="requesting">Requesting</span>
  <% elsif borrowing.status == 1 %>
    <%= f.submit "Renew", class: "btn btn-primary col-md-1"%>
    <span id="approve">Appoved</span>
  <% else %>
    <%= f.submit "Renew", class: "btn btn-primary col-md-1", disabled: true%>
    <span id="requesting">Renew requesting</span>
  <% end %>

<% end %>

app/views/borrowings/borrowing_all.html.erb
<h1>Dashboard</h1>


<% if !@borrowings.nil? %>
<%= will_paginate %>

<ul class="users">
	<%= render @borrowings %>
</ul>

<%= will_paginate %>
<% end %>

app/views/borrowings/create.js.erb
$("#borrow_form").html("<%= escape_javascript(render('books/unborrow')) %>");
$("#update_availability").html("<%= escape_javascript(render('books/update_availability')) %>");

app/views/borrowings/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/borrowings/index.html.erb
<h1>Dashboard</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @borrowings %>
</ul>

<%= will_paginate %>

app/views/borrowings/return_book.html.erb
<h1>Return Book</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
    <%= form_tag(return_path, method: "get", class: "row") do %>
      <%= label_tag(:user_id, "User ID:", class: "col-md-4") %>
      <%= text_field_tag(:user_id, "", class: "col-md-6") %>
      <%= submit_tag("Find user", class: "col-md-3 btn btn-primary") %>
    <% end %>
  </div>
</div>


<% if !@borrowings.nil? %>
	<%= will_paginate %>
		<ul class="users">
			<%= render @borrowings %>
		</ul>
	<%= will_paginate %>
<% end %>