config/routes.rb
Rails.application.routes.draw do
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'

  get '/signup', to: 'users#new'
  resources :users
  post '/signup', to: 'users#create'
  resources :account_activations, only: [:edit]

  resources :books

  resources :borrowings,       only: [:index, :create, :destroy, :update]
  get '/borrowing/all', to: "borrowings#borrowing_all"
  patch '/approve', to: "borrowings#approve"
  patch '/deny_renew', to: "borrowings#deny_renew_request"
  patch '/deny_borrow', to: "borrowings#deny_borrow_request"
  get '/return', to: "borrowings#return_book"

  get '/search', to: 'search#search'


  resources :return_books, only: [:index]

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :catalog
  validates :user_id, presence: true
  validates :title, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: -1 }

  scope :title, -> (title) { where("title like ?", "%#{title}%")}
  scope :author, -> (author) { where("author like ?", "%#{author}%")}

  def available?
  	if self.availability > 0
  		return true
  	else
  		return false
  	end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :librarian_user, only: [:new, :create, :update, :destroy, :edit]

	def new
		@catalogs = Catalog.all
		@book = Book.new
	end

	def show
		@book = Book.find(params[:id])
	end

	def index
		@books = current_user.borrowing.paginate(:page => params[:page])
	end

	def create
		params[:book][:availability] = params[:book][:quantity]
		@book = current_user.books.build(book_params)
		if @book.save
			flash[:success] = "Book created!"
			redirect_to @book
		else
			@catalogs = Catalog.all
			render 'new'
		end
	end

	def edit
		@catalogs = Catalog.all
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		@book[:availability] -= @book[:quantity].to_i - params[:book][:quantity].to_i

		if @book.update_attributes(book_params)
			flash['success'] = "Book updated!"
			redirect_to @book
		else
			render 'edit'
		end
	end

	def destroy
		Book.find(params[:id]).destroy
		flash[:success] = "Book deleted"
		redirect_to request.referrer || root_url
	end

	private

		def book_params
			params.require(:book).permit(:title, :publisher, :year, :quantity, :author, :catalog_id, :dewey_id, :availability)
		end

		def librarian_user
			if current_user.nil?
				redirect_to (login_url)
			else
				redirect_to (login_url) unless current_user.librarian?
			end
		end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<li>
  <%= link_to book.title, book %>
  <p>Author: <%= book.author %></p>
  <p>Availability: <%= book.availability %></p>
  <p>Year: <%= book.year %></p>

  <% if current_user && current_user.librarian? %>
    | <%= link_to "delete", book, method: :delete,
                                  data: { confirm: "You sure?" } %>
    | <%= link_to "edit", edit_book_path(book) %>
  <% end %>
  
</li>

app/views/books/_borrow_form.html.erb
<% if @book.available? %>
	<div id="borrow_form">
		<% if !current_user.borrowing?(@book) %>
			<%= render 'borrowing' %>
		<% else %>
			<%= render 'unborrow' %>
		<% end %>
	</div>
<% else %>
	<button type="button" class="btn btn-default" disabled="true">Unavailable</button>
<% end %>

app/views/books/_borrowing.html.erb
<%= form_for(current_user.borrowings.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :book_id, @book.id %></div>
  <%= f.submit "Borrow", class: "btn btn-primary col-md-3" %>
<% end %>

app/views/books/_unborrow.html.erb
<p class="label label-default">Requested</h1>

app/views/books/_update_availability.html.erb
<div id="update_availability"><p>Availability: <%= @book.availability %></p></div>

app/views/books/edit.html.erb
<h1>Update Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.label :catalog %>
      <%= f.select :catalog_id, @catalogs.map{ |c| [c.name, c.id] } %>

      <%= f.label :year %>
      <%= f.number_field :year, class: 'form-control', min: 0 %>

      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control', min: 0 %>

      <%= f.submit "Update book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/index.html.erb
<h1>All books</h1>


<% if current_user && current_user.librarian? %>
	<div class="center">
		<%= link_to "Create book", new_book_path, class: "btn btn-primary" %>
	</div>
<% end %>

<%= will_paginate %>

<ul class="users">
	<%= render @books %>
</ul>

<%= will_paginate %>

app/views/books/new.html.erb
<% provide(:title, 'New Book') %>
<h1>New Book</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@book) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :publisher %>
      <%= f.text_field :publisher, class: 'form-control' %>

      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>

      <%= f.label :catalog %>
      <%= f.select :catalog_id, @catalogs.map{ |c| [c.name, c.id] } %>

      <%= f.label :year %>
      <%= f.number_field :year, class: 'form-control', min: 0 %>

      <%= f.label :quantity %>
      <%= f.number_field :quantity, class: 'form-control', min: 0 %>

      <%= f.submit "Create book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/books/show.html.erb
<% provide(:title, @book.title) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1> Title: 
        <%= @book.title %>
      </h1>
      <p>Author:
        <%= @book.author %>
      </p>
      <p>Publisher:
        <%= @book.publisher %>
      </p>                                              
      <p>Year:
        <%= @book.year %>
      </p>
      <p>Quantity:
        <%= @book.quantity %>
      </p>
      <div id="update_availability"><p>Availability: <%= @book.availability %></p></div>

      <% if logged_in? %>
        <% if !current_user.librarian? %>
          <%= render 'borrow_form'%>
        <% else %>
          <%= link_to "Edit", edit_book_path, class: "btn btn-primary" %>
        <% end %>
      <% end %>
    </section>
  </aside>
</div>