config/routes.rb
Rails.application.routes.draw do
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'

  get '/signup', to: 'users#new'
  resources :users
  post '/signup', to: 'users#create'
  resources :account_activations, only: [:edit]

  resources :books

  resources :borrowings,       only: [:index, :create, :destroy, :update]
  get '/borrowing/all', to: "borrowings#borrowing_all"
  patch '/approve', to: "borrowings#approve"
  patch '/deny_renew', to: "borrowings#deny_renew_request"
  patch '/deny_borrow', to: "borrowings#deny_borrow_request"
  get '/return', to: "borrowings#return_book"

  get '/search', to: 'search#search'


  resources :return_books, only: [:index]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "capstone app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_url %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Search", search_path  %></li>
        <% if logged_in? %>
          <% if current_user.librarian? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Book <b class="caret"></b>
              </a>

              <ul class="dropdown-menu">
                <li><%= link_to "Borrowing Books", borrowing_all_path %></li>
                <li><%= link_to "Requesting Books", borrowings_path %></li>
                <li><%= link_to "Return Book", return_books_path %></li>
              </ul>
            </li>
          <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
          </a>

          <ul class="dropdown-menu">
            <li><%= link_to "Dashboard", borrowings_path %></li>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>          
        <% end %>

       <!--  <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li> -->
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>